### ISSUE TITLE
Sending a fax doesn't work

### ISSUE THREAD

**Issue by wintermeyer** [amooma/GS5#178]
URL which triggered the bugreport is: /users/1/fax_accounts
GS5 buildname: 1302161208 (5.1-beta5)

A new uploaded fax doesn't get faxed. It just waits in the queue.

**Comment by spag** [comment]
I could not replicate this behavior on the gs5_1302141223.iso, going to check out gs5_1302161208.iso

**Comment by spag** [comment]
I can not replicate this issue with the gs5_1302161208 either.

One thing that seems to be different from previous versions is that on the the newer builds (1302141223 included) FreeSWITCH is not running after the installation is finished and one has to start it manually.

So if "doesn't get faxed" actually means "doesn't get faxed because there is no FreeSWICH process to handle it" we  have probably nailed it.

**Comment by wintermeyer** [comment]
I opened https://github.com/amooma/GBE/issues/153 for this issue.
