### ISSUE TITLE
"Missed Calls" List in Snom 360

### ISSUE THREAD

**Issue by matis2le** [amooma/GS5#196]
inconsitency regarding the Phone UI: - you can not delete (or set read) an missed call except you pick up the handset and use the menu item "pool"

**Comment by wintermeyer** [comment]
@spag: Bug or feature?

**Comment by spag** [comment]
What I have to do to replicate this issue?

**Comment by matis2le** [comment]
i had installed a 5.1b5 and connected it with sipgate, flashed a Snom 360 with 8.4.35 and connected it to an account i prepared before. If a call comes and was missed - there is  a message on the display "1 Missed"
The only way i found to set this to read is to lift the handset and then comes the menu "pool" where i found the list and can delete the missed call. 
All other Buttons i tested dosn't go to this list or had no possibility to set it to read or delete....
Sorry for my ugly english!

**Comment by spag** [comment]
Sorry, but I can not replicate this issue. I have tested it on a Snom 360 and Snom 821 and on both phones the "1 Missed" line disappears instantly after pressing the 'X' button ("cancel" button left of the rocker key on Snom 360 phones) as it does on virtually every other Snom model.
If you are sure this issue is GS5 related and not caused by faulty hardware please feel free to reopen this issue.

**Comment by matis2le** [comment]
Oha... that kind of behavior you need to know.... its not very logical! And dismissing is the only choice you have...??
It would be better to make it a soft button to open the list, use the number or delete it!
Anyway - its up to you!
